SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 750
FPS = 20
BULLET_RADIUS = SCREEN_WIDTH / 100
BOMB_RADIUS = SCREEN_WIDTH / 50
LASER_DIST = SCREEN_WIDTH / 100
GRAVITY = 9.8 * 25

# Projectile constants
BULLET_MASS = SCREEN_WIDTH / 1.5
BOMB_MASS = SCREEN_WIDTH / 2
BULLET_MAX_VEL = BULLET_MASS
BOMB_MAX_VEL = BOMB_MASS
LASER_VEL = SCREEN_WIDTH / 1.5
BULLET_GRAVITY = True
BOMB_GRAVITY = True
LASER_GRAVITY = False
BOMB_DRILL = SCREEN_WIDTH / 20
LASER_IMPULSE = SCREEN_WIDTH / 20